### ISSUE TITLE
Few previously matching codes no longer match

### ISSUE THREAD

**Issue by umairzahmed** [iradicek/clara#14] opened 2020-01-20 03:55 UTC
#11 After the recent bug fix, the following codes don't match (that is, they used to match earlier). Filing as bug since I think they should match using ILP.

```
$ cat p_1.c
#include<stdio.h>

int main(){
  int n, s1=0, s2=0;
  scanf("%d", &n);

  for(int i=1; i<=n; i++){
    s1  = i*(i+1)/2;
    s2 += s1;
  }

  printf("%d", s2);
  return 0;
}

$ cat p2.c
#include<stdio.h>

int main(){
  int n, s1=0, s2=0;	
  scanf("%d", &n);

  for(int i=1; i<=n; i++){
    s1 += i;
    s2 += s1;
  }

  printf("%d", s2);
  return 0;
}

$ clara match p1.c p2.c --entryfnc "main" --ins "[[4]]"
No match!
```

**Comment by umairzahmed** [comment] 2020-01-20 04:13
Another example: For vs While loop, which used to match earlier
```
 cat p_3.c
#include<stdio.h>

int main(){
  int i=1, sum=0, n;
  scanf("%d", &n);

  for(i; i<=n; i++){
    sum += i;

  }

  printf("%d", sum);
  return 0;
}

$ cat p4.c
#include<stdio.h>

int main(){
  int i=1, sum = 0, n;
  scanf("%d",&n);

  while(i<=n){
    sum += i;
    i++;
  }

  printf("%d",sum);
  return 0;
}

$ clara match p3.c p4.c --entryfnc "main" --ins "[[4]]"
No match!
```

**Comment by iradicek** [comment] 2020-02-02 16:04
The first one not matching was a regression bug. It's fixed now. And it also made me realize that there should be some kind of regression testing :) The second example should not match because control-flows are not completely the same. If you need the behaviour that the second example matches we could add a special flag so that the control-flow is rewritten to the same form.

**Closed by iradicek** 2020-02-02 16:04 UTC
